### ISSUE TITLE
Pointgrey camera too hot

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/teo-head#31]
Pointgrey camera heats a lot even when not in use, which leads to hardware livespan reduction (and other potential problems)

**Comment by David-Estevez** [comment]
I am currently making some tests _ex vivo_ to determine if is a problem of the camera, its a normal condition of if it is related to the camera environment inside TEO head.

**Comment by David-Estevez** [comment]
_In vivo_ tests:
- Camera connected to the head PC, inside TEO head: camera gets hot as hell (i.e. hot as the DC-DC converter heatsink) :fire: :fire:.
- Camera disconnected, inside TEO head: camera at room temperature.

_Ex vivo_ tests:
- Camera connected to another computer, outside TEO head, drivers not installed: camera gets warm, but not too hot.
- Camera connected to another computer, outside TEO head, drivers installed (capture running or stopped, it's the same): camera gets hot as hell (i.e. hot as the DC-DC converter heatsink) :fire: :fire:.

**Comment by smcdiaz** [comment]
Antes de haber hecho nada lo normal hubiera sido medir la temperatura y consultar las características de la cámara. From the manual:

The Flea2 is an ultra-compact camera. As a result of packing the Flea2 electronics into a small
space, the outer case of the camera can become very warm to the touch when running in some
high data rate video modes. The case can reach temperatures up to 45° Celsius under normal
operating conditions. This is expected behaviour and will not damage the camera electronics.

Temperatura >>> 45º ->instalamos ventilador
Temperatura <= 45º OK!! no es necesaria la ventilación forzada

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#8
