### ISSUE TITLE
Merge haarDetection2D+colorRegionDetection2D programs

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-head#79]
Merge haarDetection2D+colorRegionDetection2D programs

**Comment by davidvelascogarcia** [comment]
Regarding #79 issue i´ve been trying to merge `colorRegionDetection` /` colorRegionDetection2D` and `haarDetection` / `haarDetection2D`.
First, i´ve started trying to merge `colorRegionDetection2D` with `haarDetection2D`. 
Updates in [vision](https://github.com/davidvelascogarcia/vision/tree/haarColorRegionDetection2D) fork , `haarColorRegionDetection2D` branch. Right now works correctly at the same time and publish the results in two different ports `haar` and `colorRegion` ports.  
I have to check features ports, it is added but i haven´t test yet.
Picture test attached.

![testhaarColorRegionDetection](https://user-images.githubusercontent.com/29423648/68600248-76a59e80-04a2-11ea-8b65-e9e7a175cc47.png)
Figure 1. Test haar and color region detection

Regarding the name, i didn´t know the name to be selected and now i have named as `haarColorRegionDetection2D`, as fusion´s name.
@jgvictores what do you thing about that?

**Comment by PeterBowman** [comment]
Is it worth in terms of efficiency having this app perform two different tasks at once?

**Comment by jgvictores** [comment]
Nope! @davidvelascogarcia and I have spoken regarding the proposed architecture. It would look more like the following:

![photo_2019-11-11_17-09-13](https://user-images.githubusercontent.com/4448588/68602152-203a5f00-04a6-11ea-8e80-e520208c068c.jpg)

**Comment by PeterBowman** [comment]
Looks nice. I'd keep those libs embedded within the haarColorRegionDetection2D application, unless you're really sure this could be highly reusable (given the heavy YARP constraints, I'm not sure about it). I presume that switching between modes is going to be done on init via YARP option?

**Comment by jgvictores** [comment]
I was not thinking in keeping the `haarColorRegionDetection2D` name. My original idea intended to be able to switch to tensorflow too.

Yes, I guess the config will involve passing a YARP option. The API will involve passing a YARP image and getting the features in return.

**Comment by davidvelascogarcia** [comment]
I have been working with proposed architecture in [switchDetection2D](https://github.com/davidvelascogarcia/vision/tree/switchDetection2D) branch. 
The name that i´ve selected provisionally is `switchDetection2D`.

`switchDetection2D` module, merge vision `detection2D` programs. The module merge `colorRegionDetection2D`, `haarDetection2D` and `tensorflowDetection2D`. 
This module works with `segmentorThread`. Using vision `detection2D` programs structure. 
Build an object of selected detection mode, the mode process the image received  and return the processed image and results, to be published.
PR at [#78](https://github.com/roboticslab-uc3m/vision/pull/98).

The process diagram attached in Figure 1.
![swicthDetection](https://user-images.githubusercontent.com/29423648/69546510-2fd0a200-0f94-11ea-859f-147dc60caccf.jpg)
Figure 1. Diagram

Now i´m going to add [Transformation](https://github.com/roboticslab-uc3m/tools/blob/develop/libraries/YarpPlugins/RealToSimControlboard/Transformation.hpp) class to build the selected detector objects using parameters objects instead of each parameter individually.

**Comment by jgvictores** [comment]
Edited description because it was way too ambitious. Enough has been done at https://github.com/roboticslab-uc3m/vision/commit/7497b4b07688aafa101889f5285abddc1c16c427 (see commit message for more tasks that were accomplished in the process):
- Old: colorRegionDetection2D + haarDetection2D
- New: switchDetection2D + libs (HaarDetector + ColorRegionDetector)
